[settings]
provider = "native"

[relaychain]
default_command = "./polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9955
ws_port = 9955

# First parachain
[[parachains]]
id = 1000

[parachains.collator]
name = "charlie"
rpc_port = 9988
ws_port = 9988
command = "./target/release/parachain-template-node"

# Second parachain
[[parachains]]
id = 2000

[parachains.collator]
name = "dave"
rpc_port = 9999
ws_port = 9999
command = "./target/release/parachain-template-node"