[settings]
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9955

[[parachains]]
id = 1000

[metrics]
enabled = false

[parachains.collator]
name = "charlie"
rpc_port = 9988
command = "parachain-template-node"