[relaychain]
default_command = "polkadot-omni-node"
chain_spec_path = "./relay-raw.json"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000
chain_spec_path = "./dev_chain_spec.json"

[parachains.collator]
name = "charlie"
rpc_port = 9988
command = "parachain-template-node"
